channel:        #test
subreddit:		all
owner:          me
useAuth:        true
name:			|debug|
authName:       botDebug
authPassword:   
debug:          false
handler:        de.kuschku.ircbot.chathandlers.ChatRedditHandler,de.kuschku.ircbot.chathandlers.ControlHandler,de.kuschku.ircbot.chathandlers.ShipHandler,de.kuschku.ircbot.chathandlers.LinkTitleHandler