channel:        #frozen
owner:          kuschku
useAuth:        false
authName:       kBotDebug
authPassword:   
debug:          false
handler:        chathandlers.ChatRedditHandler,chathandlers.ControlHandler,chathandlers.SongHandler